# Generated by Django 5.2.7 on 2025-11-25 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("slug", models.SlugField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "products",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("brand", models.CharField(default="un-branded", max_length=250)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("slug", models.SlugField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.ImageField(upload_to="products/")),
            ],
            options={
                "verbose_name": "categories",
            },
        ),
    ]
