# Generated by Django 5.2.7 on 2025-12-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_orderitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
