# Generated by Django 5.2.5 on 2025-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('paid', 'Paid'), ('pending', 'Pending')], default='pending'),
        ),
    ]
